const slovnik = {
'(to be) fast asleep': ['tvrdě spát'],
Africa: ['Afrika'],
America: ['Amerika'],
Asia: ['Asie'],
Bohemia: ['Čechy'],
Bulgaria: ['Bulharsko'],
Cinderella: ['Popelka'],
Earth: ['Země (planeta)'],
Europe: ['Evropa'],
'I am fond of': ['mám rád'],
'I will jump too': ['budu také skákat'],
'I will skip too': ['budu také hopsat, poskakovat'],
Moon: ['Měsíc'],
'O. K.': ['dobrá'],
October: ['říjen'],
Poland: ['Polsko'],
'Sit still.': ['Seď klidně.'],
Soviet: ['sovětský'],
Sun: ['Slunce'],
'That doesn\'t matter.': ['Na tom nezáleží.'],
'What\'s the matter?': ['Co se děje?'],
Zoo: ['zoo'],
'a few shops': ['několik obchodů'],
'a few': ['několik'],
'a hundred': ['sto'],
'a little': ['trochu'],
'a thousand': ['tisíc'],
absent: ['nepřítomný'],
ache: ['bolet,bolest'],
actually: ['opravdu,vlastně'],
adult: ['dospělý'],
again: ['zase,znovu'],
age: ['věk'],
air: ['vzduch'],
'alarm clock': ['budík'],
along: ['podél'],
among: ['mezi'],
anniversary: ['výročí'],
annoying: ['mrzutý,otravný'],
another: ['jiný, další, ještě jeden'],
'apart from': ['kromě,jinak'],
area: ['plocha, prostor'],
around: ['kolem, okolo'],
arrive: ['přijít, přijet'],
'as-as': ['tak-jako, stejně-jako'],
as: ['jako'],
atmosphere: ['ovzduší, atmosféra'],
attend: ['navštěvovat, účastnit se'],
attic: ['podkroví,mansarda'],
aunt: ['teta'],
back: ['záda'],
background: ['pozadí'],
badge: ['odznak'],
balloon: ['balón, balónek'],
bargain: ['výhodně koupené zboží'],
bat: ['pálka'],
bath: ['vana'],
battery: ['baterie'],
'be fond of': ['mít rád'],
'be married': ['být ženatý'],
'be on': ['být na programu'],
bear: ['medvěd'],
beat: ['bít'],
become: ['stát se'],
bed: ['postel'],
bedroom: ['ložnice'],
bee: ['včela'],
before: ['před'],
begin: ['začít'],
beginning: ['začátek'],
behind: ['za'],
believe: ['věřit'],
bend: ['ohnout (se)'],
biology: ['biologie'],
bird: ['pták'],
birdhouse: ['ptačí budka'],
birth: ['narození'],
biscuit: ['sušenka'],
blazer: ['sportovní sako, bunda'],
blow: ['foukat, odfouknout'],
boaster: ['chvastoun, chlubil'],
body: ['(nebeské) těleso'],
bowl: ['koulet,'],
'bread crumbs': ['chlebové drobečky'],
break: ['přestávka'],
'bright-eyed': ['bystrooký, s bystrýma očkama'],
broom: ['koště, smeták'],
brush: ['kartáč(ek); čistit'],
bush: ['keř, keřík'],
busy: ['zaneprázdněný,v jednom kole'],
'by twos': ['po dvou'],
cage: ['klec'],
cake: ['koláč, dort'],
calendar: ['kalendář'],
camel: ['velbloud'],
canteen: ['jídelna (školní, závodní)'],
care: ['péče'],
catalogue: ['katalog'],
celebration: ['oslava'],
'cellular phone': ['mobilní telefon'],
'central heating': ['ústřední topení'],
certainly: ['jistě, určitě'],
chalk: ['křída'],
chance: ['možnost,příležitost'],
charger: ['nabíječka'],
cheerful: ['radostný, šťastný'],
chimney: ['komín'],
choice: ['výběr,volba,tip'],
chop: ['useknutý kousek masa,'],
circle: ['kruh; kroužit'],
clear: ['jasný'],
close: ['zavírat,těsný,sevřený'],
closest: ['nejblíže'],
clothes: ['šaty,oblečení'],
cloudy: ['zamračený, ob-'],
club: ['klub'],
cluster: ['shluknout se'],
coal: ['uhlí'],
coat: ['plášť,kožíšek'],
collect: ['sbírat'],
collection: ['sbírka'],
collector: ['sběratel'],
'coloured people': ['barevní lidé'],
competition: ['soutěž'],
convenient: ['výhodný,pohodlný'],
'cooperative farm': ['zemědělské družstvo'],
corner: ['roh,kout'],
cosmonaut: ['kosmonaut'],
cotton: ['bavlna'],
'count a hundred': ['počítat do sta'],
cricket: ['kriket'],
cross: ['přejít (přes ulici)'],
crumb: ['drobek, drobeček'],
cry: ['plakat,křičet'],
cuddly: ['roztomilý,pomilováníhodný'],
cultural: ['kulturní'],
curtain: ['záclona'],
cut: ['krájet, ukrojit'],
dandelion: ['pampeliška'],
deep: ['hluboký, hluboko'],
defective: ['vadný,defektní'],
demonstration: ['manifestace'],
dentist: ['zubní lékař'],
different: ['jiný, odlišný'],
disappointed: ['zklamaný'],
discussion: ['diskuse'],
'do hair': ['česat se, dělat si účes'],
'do sport, go in for sport': ['pěstovat sport'],
down: ['dolů,dole,'],
drawer: ['zásuvka'],
'drive away': ['odhánět'],
driveway: ['příjezdová cesta'],
driving: ['řízení,jízda autem'],
droppings: ['trus'],
dry: ['suchý'],
dull: ['nudný'],
during: ['během, v průběhu'],
duster: ['prachovka'],
each: ['každý'],
easily: ['snadno'],
east: ['východ'],
easy: ['snadný'],
eaves: ['okap'],
education: ['výchova,vzdělání'],
egg: ['vejce'],
eggs: ['vejce (mn. č.)'],
elephant: ['slon'],
empty: ['prázdný'],
enjoy: ['líbit se,užít si,těšit se z něčeho'],
entrance: ['vchod'],
escalator: ['pohyblivé schody'],
especially: ['obzvláště'],
even: ['i, dokonce'],
everybody: ['každý, všichni'],
everywhere: ['všude'],
exactly: ['přesně'],
except: ['kromě, vyjma'],
exhausted: ['vyčerpaný'],
exhibition: ['výstava'],
explain: ['vysvětlit'],
factory: ['továrna'],
'fair lady': ['krásná paní'],
farewell: ['mít se dobře,sbohem,žijte blaze'],
farmer: ['rolník, zemědělec'],
favourite: ['oblíbený'],
fear: ['bát se'],
fellow: ['chlapík, zde: kluk'],
fetch: ['přinést'],
fight: ['bojovat'],
'figure skating': ['krasobruslení'],
fill: ['plnit'],
finish: ['končit'],
fireman: ['požárník, hasič'],
firewood: ['palivové dříví'],
fish: ['ryba'],
fix: ['upevnit, připevnit'],
flat: ['byt'],
foam: ['pěna'],
foe: ['nepřítel, protivník'],
food: ['jídlo, krmení'],
for: ['neboť'],
form: ['třída,pelech'],
freeze: ['mrznout'],
fresh: ['čerstvý'],
friendly: ['stávají se přátelskými'],
fur: ['kožešina'],
fuss: ['povyk, rozruch'],
future: ['budoucnost'],
gallery: ['galérie'],
'garage hand': ['pracovník v garáži, automechanik'],
gather: ['shromáždit se'],
gay: ['veselý'],
gently: ['mírně, něžně'],
geography: ['zeměpis'],
giraffe: ['žirafa'],
glad: ['rád'],
gliding: ['klouzavý'],
good: ['hodný, hodná'],
granddad: ['dědeček'],
grass: ['tráva'],
grasshopper: ['kobylka luční'],
grey: ['šedý'],
'ground floor': ['přízemí'],
group: ['skupina'],
'grow stronger': ['sílit,zesílit'],
gym: ['tělocvik'],
gymnasium: ['tělocvična'],
hang: ['věšet, pověsit'],
happen: ['stát se'],
'hard to spy': ['které se těžko hledají'],
hardly: ['stěží,sotva'],
hare: ['zajíc'],
harm: ['škoda, ublížení'],
harvest: ['žně'],
hat: ['klobouk'],
'have not won': ['neuspěl jsi'],
head: ['hlava'],
healthy: ['zdravý'],
heart: ['srdce'],
hedge: ['živý plot'],
hill: ['pahorek, kopec'],
history: ['dějepis'],
hit: ['udeřit,uhodit,odpálit'],
hive: ['úl'],
hole: ['jáma, díra'],
hood: ['kapuce'],
hop: ['skákat'],
hope: ['naděje; doufat'],
house: ['dům'],
hungry: ['hladový'],
hurt: ['bolet,ublížit,ubližovat'],
'ice rink': ['kluziště'],
icy: ['ledový,zmrzlý,zledovatělý'],
if: ['jestliže'],
ill: ['nemocný'],
illuminate: ['osvětlovat'],
important: ['důležitý'],
'in ones': ['jednotlivě, po jednom, za sebou'],
'in order': ['aby'],
'in person': ['osobně'],
'in twos': ['ve dvojicích,po dvou'],
indeed: ['skutečně, doopravdy'],
industrial: ['průmyslový'],
insect: ['hmyz'],
interesting: ['zajímavý'],
interschool: ['meziškolní'],
introduce: ['představovat (někoho někomu)'],
'iron bar': ['železná tyč'],
'it makes me laugh': ['to mě rozesměje'],
'it was due': ['očekávalo se'],
'it\'s a shame': ['to je škoda'],
jolly: ['veselý'],
just: ['právě'],
'keep the rule': ['dodržuj pravidlo'],
'keep up': ['udržet se nahoře'],
keep: ['držet (se čeho),dodržovat,chovat'],
kind: ['druh'],
knife: ['nůž'],
knock: ['klepat, zaklepání'],
lake: ['zde: velký rybník'],
lamb: ['jehně, jehněčí'],
lamp: ['lampa'],
language: ['řeč, jazyk'],
later: ['později'],
laugh: ['smát se; smích'],
'lay the table': ['prostřít stůl'],
leader: ['vůdce, vedoucí'],
'leap year': ['přestupný rok'],
leap: ['skákat,skočit'],
leaves: ['listy, listí'],
life: ['život'],
lion: ['lev'],
literature: ['literatura'],
'little things': ['tvorečkové'],
log: ['poleno,špalek,kláda'],
'looking-glass,mirror': ['zrcadlo'],
'looks like': ['vypadá jako'],
lose: ['ztratit'],
lump: ['kousek, kostka (cukru)'],
lunch: ['oběd, přesnídávka'],
machine: ['stroj'],
man: ['muž,člověk,'],
'maternity hospital': ['porodnice'],
matter: ['věc, záležitost,'],
meadow: ['louka'],
mean: ['znamenat'],
meat: ['maso'],
meeting: ['schůze, schůzka'],
member: ['člen'],
mention: ['zmínit se'],
merry: ['veselý'],
mice: ['myši'],
might: ['moc, síla'],
'mind the clock': ['všímej si hodin,dávej pozor na hodiny'],
mind: ['dát si pozor, všimnout si'],
mixed: ['smíšený'],
model: ['model, vzor'],
mole: ['krtek'],
monkey: ['opice'],
month: ['měsíc (kalendářní)'],
most: ['většina'],
motorway: ['dálnice'],
'mouse,mice': ['myš,myši'],
mousetrap: ['past na myši'],
'much closer': ['mnohem blíž'],
'neither nor': ['ani ani'],
nephew: ['synovec'],
nest: ['hnízdo, skrýše'],
'never mind': ['nevadí'],
'never we part': ['nikdy se s ním nerozloučíme'],
'newspaper ad': ['novinový inzerát'],
'next time': ['příště'],
night: ['noc'],
'no matter how hard we try': ['ať se snažíme jak chceme'],
nobody: ['nikdo'],
nod: ['kývnout (na pozdrav)'],
north: ['sever'],
notice: ['oznámení'],
nut: ['ořech, oříšek'],
nutting: ['sbírání oříšků'],
'o\'er': ['over'],
official: ['úřední, oficiální'],
'on foot': ['pěšky'],
once: ['jednou'],
others: ['jiní, jiné'],
out: ['ven'],
outside: ['mimo,za,venku'],
outskirts: ['předměstí,okolí města'],
paperback: ['brožovaná kniha'],
parcel: ['balíček'],
part: ['část'],
pass: ['kráčet vpřed,procházet'],
past: ['minulost'],
patient: ['trpělivý'],
peace: ['mír'],
peaceful: ['poklidný,pokojný,mírumilovný'],
peas: ['hrášek'],
pension: ['důchod,penze'],
performance: ['představení'],
'pest controller': ['deratizátor'],
phone: ['telefon'],
picnic: ['výlet do přírody spojený s obědem'],
pie: ['koláč'],
'pile-up': ['řetězová srážka'],
pincers: ['kleště'],
'pitter-patter': ['ťapkání'],
pity: ['škoda, lítost'],
placard: ['plakát'],
plain: ['plošina, nížina'],
plan: ['plán; plánovat'],
planet: ['planeta'],
plant: ['vysadit, zde: zasít'],
platform: ['nástupiště'],
player: ['hráč'],
please: ['potěšit'],
pleasure: ['potěšení,rozkoš'],
'plenty of': ['množství, spousta'],
plenty: ['množství, spousta'],
pocket: ['kapsa'],
point: ['bod'],
'polar bear': ['lední medvěd'],
polar: ['polární'],
poor: ['zde: slabý'],
popular: ['oblíbený, populární'],
population: ['obyvatelstvo'],
porch: ['veranda, krytý vchod'],
port: ['přístav'],
potato: ['brambor'],
'prefer (to)': ['dávat přednost (před)'],
present: ['dárek'],
pretty: ['pěkný,hezký,půvabný'],
probably: ['pravděpodobně'],
produce: ['vyrábět'],
promise: ['slíbit, slib'],
proud: ['pyšný,hrdý'],
pudding: ['pudink'],
puddle: ['louže, kaluž'],
'pull out': ['vytáhnout'],
pull: ['táhnout,tahat'],
pullover: ['pulover, pletené'],
pussy: ['kočička'],
queue: ['řada, fronta'],
quickly: ['rychle'],
rabbit: ['králík'],
race: ['závod,spěchat,uhánět'],
rag: ['hadr, cár'],
rail: ['zábradlí'],
rain: ['déšť'],
raincoat: ['plášť do deště'],
rainy: ['deštivý'],
rank: ['řada, šik'],
rap: ['klepat'],
'rather a lot': ['poměrně dost'],
ray: ['paprsek'],
reach: ['dosáhnout,dostihnout'],
ready: ['připravený, hotový'],
real: ['skutečný'],
really: ['skutečně'],
receive: ['dostat, obdržet'],
record: ['gramofonová deska,záznam'],
reflect: ['odrážet'],
rest: ['zbytek'],
rhyme: ['rým, říkadlo'],
rich: ['bohatý'],
'ring up': ['zatelefonovat'],
ripe: ['zralý'],
rise: ['vstávat,'],
roast: ['péci'],
rocket: ['raketa'],
'roll along': ['kolébat se'],
roll: ['rohlík'],
roof: ['střecha'],
room: ['místnost,pokoj'],
rope: ['lano'],
'rose-bush flower': ['růžový květ'],
round: ['kulatý'],
rule: ['pravidlo'],
sales: ['výprodej'],
satellite: ['satelit, družice'],
saucer: ['podšálek, talířek'],
saw: ['pila'],
saying: ['rčení'],
screwdriver: ['šroubovák'],
scrub: ['drhnout'],
scurry: ['uhánět'],
sea: ['moře'],
seedy: ['plný semen'],
shave: ['holit se'],
shed: ['ronit'],
sheep: ['ovce'],
shirt: ['košile'],
shy: ['plachý'],
sign: ['stopa,známka'],
since: ['od (té doby)'],
single: ['jednotlivý, jeden'],
sir: ['pane (v oslovení)'],
skiing: ['lyžování'],
sleep: ['spát'],
sliding: ['smekavý, pohyblivý'],
'slow down': ['zpomalit'],
slow: ['pomalý'],
snow: ['sníh'],
snowman: ['sněhulák'],
'so-called': ['takzvaný'],
soap: ['mýdlo'],
soldier: ['voják'],
soon: ['brzy'],
sore: ['bolavý'],
sound: ['znít, zvuk'],
soup: ['polévka'],
source: ['zdroj,pramen'],
south: ['jih'],
spare: ['náhradní,rezervní'],
special: ['speciální,zvláštní'],
speech: ['řeč, proslov'],
speed: ['hnát se, letět'],
squeak: ['vrzat'],
squirrel: ['veverka'],
stair: ['schodiště'],
stall: ['stánek'],
stick: ['hůl'],
still: ['tichý,klidný,přece'],
stocking: ['punčocha'],
stone: ['kámen'],
store: ['obchod'],
stoves: ['kamna'],
straight: ['přímý, přímo'],
strange: ['zvláštní, divný'],
stretchsuit: ['dupačky'],
strife: ['spor, konflikt'],
struggle: ['zápas, boj'],
study: ['studovat'],
subject: ['předmět'],
such: ['takový'],
sufficient: ['dostatečný'],
supper: ['večeře'],
'supper\'s over': ['je po večeři'],
surgery: ['chirurgie'],
sweep: ['zametat'],
'table tennis': ['stolní tenis'],
table: ['stůl'],
'take care (of)': ['pečovat, starat se (o)'],
'teams of ten': ['družstva po deseti,desetičlenná družstva'],
tear: ['slza'],
tears: ['slzy'],
temperature: ['teplota'],
tennis: ['tenis'],
'that\'s why': ['proto'],
'the Danube': ['Dunaj'],
'the Earth': ['(planeta) Země,'],
'the Elbe': ['Labe'],
'the Moon': ['Měsíc'],
'the Sun': ['Slunce'],
'the Zoo': ['zoologická zahrada'],
'the other': ['(ten) druhý'],
'the others': ['(ti) druzí, (ti) ostatní'],
'the same': ['tentýž'],
theatre: ['divadlo'],
'they stay that way': ['takoví zůstanou'],
though: ['ačkoliv'],
throat: ['krk, hrdlo'],
'ticket collector': ['výběrčí jízdenek'],
'tidy up': ['uklízet'],
tie: ['vázanka, kravata'],
tiger: ['tygr'],
tights: ['punčochové kalhoty'],
'till it\'s time': ['dokud není čas'],
timetable: ['jízdní řád'],
title: ['titul'],
'to advertise': ['dát inzerát,inzerovat'],
'to agree with sb.': ['souhlasit s někým'],
'to attract': ['přitahovat'],
'to be able to do something': ['moci,být schopen něco dělat'],
'to be concerned about something': ['jít o něco,týkat se něčeho'],
'to be worth doing something': ['stát za to dělat něco'],
'to carry on': ['pokračovat,chovat se hloupě'],
'to choose chose chosen': ['vybrat (si)'],
'to clear': ['odklidit,odstranit'],
'to collect dust': ['chytat prach'],
'to congratulate': ['blahopřát'],
'to contact': ['kontaktovat,spojit se s někým'],
'to deliver': ['doručit,dodat,dovézt,porodit'],
'to examine': ['prozkoumat,vyzkoušet'],
'to flash': ['blikat,zablesknout se'],
'to get time off': ['dostat volno'],
'to insist': ['trvat (na něčem)'],
'to keep': ['nechat si'],
'to last': ['vydržet,trvat'],
'to leave left left over': ['nechat,odložit (na později)'],
'to leave,left,left': ['opustit,odejít,odjet'],
'to listen to': ['poslouchat (něco)'],
'to pack up': ['zabalit'],
'to phone': ['(za)telefonovat'],
'to pick': ['vybrat si,sebrat'],
'to put down': ['položit,odložit'],
'to read': ['číst'],
'to realize': ['uvědomit si'],
'to recommend': ['doporučit'],
'to replace': ['vyměnit,nahradit'],
'to resist': ['odolávat'],
'to return': ['vrátit (se)'],
'to slide': ['klouzat'],
'to snap up': ['skoupit'],
'to suppose': ['předpokládat'],
'to take a while': ['nějakou chvíli trvat'],
'to tip': ['vyklopit,vysypat'],
'to tow': ['táhnout'],
'to wish': ['přát si'],
'to work up a sweat': ['začít se potit'],
'to write wrote written': ['psát'],
'tooth,teeth': ['zub, zuby'],
tooth: ['zub'],
toothache: ['bolení zubů'],
toothbrush: ['kartáček na zuby'],
toothpaste: ['zubní pasta'],
tortoise: ['želva'],
toy: ['hračka'],
track: ['trať'],
trailer: ['návěs'],
tribune: ['tribuna'],
trip: ['výlet, cesta'],
try: ['snažit se, pokusit se'],
trying: ['pokusy, zkoušení'],
tube: ['tuba'],
turkey: ['krocan'],
turn: ['otočit, obrátit (se)'],
typical: ['typický'],
university: ['universita'],
'up stream': ['proti proudu'],
usual: ['obvyklý'],
valuable: ['cenný'],
variation: ['střídání,změna'],
various: ['různý,rozličný'],
vegetable: ['zelenina'],
version: ['verze,varianta'],
'very few shops': ['velmi málo obchodů'],
voice: ['hlas'],
wait: ['čekat,'],
'waiting room': ['čekárna'],
'wall bars': ['ribstoly'],
'wall poster': ['plakát,nástěnka'],
wardrobe: ['šatník'],
'wash away': ['odplavat'],
waste: ['plýtvat,mrhat'],
wave: ['mávat'],
way: ['způsob'],
'we keep riding': ['stále se vozíme'],
'we seem to see': ['zdá se nám,že'],
wealthy: ['bohatý'],
wear: ['nosit (na sobě)'],
'well-kept': ['dobře udržovaný'],
west: ['západ'],
wheelbarrow: ['kolečko,trakař'],
whenever: ['kdykoli'],
while: ['dokud'],
whole: ['celý'],
wicket: ['branka'],
wife: ['manželka'],
will: ['vůle,chtění'],
willing: ['ochotný'],
wings: ['křídla'],
wise: ['moudrý,rozvážný'],
without: ['bez'],
wood: ['les,dřevo'],
word: ['slovo'],
work: ['práce,pracovat'],
'working class': ['dělnická třída'],
workshop: ['dílna'],
world: ['svět'],
'worth (reading)': ['stojí (za čtení)'],
write: ['psát'],
writer: ['spisovatel'],
'y side': ['vedle mne'],
yard: ['dvůr,dvorek'],
year: ['rok'],
yesterday: ['včera'],
'you\'ve tried': ['snažil ses'],
zoology: ['zoologie']
}
